version: "3.7"

services:
  db:
    image: mysql:5.7
    ports:
      - 4000:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  app:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
  ahk_front:
    container_name: ahk_planung_front
    image: antoniodmk/gestioneventofront:80.3
    expose: [80]
    volumes:
          - ./index.html:/usr/local/apache2/htdocs/index.html
volumes:
  mysql-data: {}
