version: "3.7"

services:
  db:
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  app:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:${PORT}
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
